PL/Models/ErrorViewModel.cs
namespace PL.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PL/Controllers/DepartamentoController.cs
using Microsoft.AspNetCore.Mvc;

namespace PL.Controllers;

public class DepartamentoController : Controller
{
    [HttpGet]
    public IActionResult GetAll()
    {
        ML.Departamento departamento = new();
        ML.Result result = BL.Departamento.GetAll();
        if (result.Correct)
        {
            departamento.Departamentos = result.Objects;
            return View(departamento);
        }
        else
        {
            return View(departamento);
        }
    }

    [HttpGet]
    public IActionResult Form(int IdDepartamento)
    {
        ML.Departamento departamento = new();
        ML.Result result = BL.Departamento.GetById(IdDepartamento);
        if (result.Correct)
        {
            departamento = (ML.Departamento)result.Object;
            return View(departamento);
        }
        else
        {
            return View(departamento);
        }
    }

    [HttpPost]
    public IActionResult Form(ML.Departamento departamento)
    {
        if (departamento.IdDepartamento == 0)
        {
            ML.Result result = BL.Departamento.Add(departamento);
            if (result.Correct)
            {
                ViewBag.Message = "Se inserto correctamente el registro";
            }
            else
            {
                ViewBag.Message = "Ocurrio un error al insertar el registro";
            }
            return PartialView("Modal");
        }
        else
        {
            ML.Result result = BL.Departamento.Update(departamento);
            if (result.Correct)
            {
                ViewBag.Message = "Se actualizo correctamente el registro";
            }
            else
            {
                ViewBag.Message = "Ocurrio un error al actualizar el registro";
            }
            return PartialView("Modal");
        }
    }

    [HttpGet]
    public IActionResult Delete(int IdDepartamento)
    {
        ML.Result result = BL.Departamento.Delete(IdDepartamento);
        if (result.Correct)
        {
            ViewBag.Message = "Se inactivo correctamente el registro";
        }
        else
        {
            ViewBag.Message = "Ocurrio un error al inactivar el registro";
        }
        return PartialView("Modal");
    }
}

PL/Controllers/EmpleadoController.cs
using Microsoft.AspNetCore.Mvc;

namespace PL.Controllers;

public class EmpleadoController : Controller
{
    [HttpGet]
    public IActionResult GetAll()
    {
        ML.Empleado empleado = new();
        ML.Result result = BL.Empleado.GetAll();
        if (result.Correct)
        {
            empleado.Empleados = result.Objects;
            return View(empleado);
        }
        else
        {
            return View(empleado);
        }
    }

    [HttpGet]
    public IActionResult Form(int IdEmpleado)
    {
        ML.Empleado empleado = new()
        {
            Departamento = new ML.Departamento()
        };
        ML.Result resultDepartamento = BL.Departamento.GetAll();
        if (IdEmpleado == 0)
        {
            empleado.Departamento.Departamentos = resultDepartamento.Objects;
            empleado.FechaIngreso = DateTime.Now.Date;
            empleado.FechaNacimiento = DateTime.Now.Date;
            return View(empleado);
        }

        ML.Result result = BL.Empleado.GetById(IdEmpleado);

        if (result.Correct)
        {
            empleado = (ML.Empleado)result.Object;
            empleado.Departamento.Departamentos = resultDepartamento.Objects;
            return View(empleado);
        }
        else
        {
            ViewBag.Message = "Ocurrio un error al consultar la informacion";
            return PartialView("Modal");
        }
    }

    [HttpPost]
    public IActionResult Form(ML.Empleado empleado)
    {
        if (empleado.IdEmpleado == 0)
        {
            ML.Result result = BL.Empleado.Add(empleado);
            if (result.Correct)
            {
                ViewBag.Message = "Se inserto correctamente el registro";
            }
            else
            {
                ViewBag.Message = "Ocurrio un error al insertar el registro";
            }
            return PartialView("Modal");
        }
        else
        {
            ML.Result result = BL.Empleado.Update(empleado);
            if (result.Correct)
            {
                ViewBag.Message = "Se actualizo correctamente el registro";
            }
            else
            {
                ViewBag.Message = "Ocurrio un error al actualizar el registro";
            }
            return PartialView("Modal");
        }
    }

    [HttpGet]
    public IActionResult Delete(int IdEmpleado, int IdSueldo)
    {
        ML.Result result = BL.Empleado.Delete(IdEmpleado, IdSueldo);
        if (result.Correct)
        {
            ViewBag.Message = "Se inactivo correctamente el registro";
        }
        else
        {
            ViewBag.Message = "Ocurrio un error al inactivar el registro";
        }
        return PartialView("Modal");
    }
}

PL/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PL.Models;
using System.Diagnostics;

namespace PL.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PL/Views/Departamento/Form.cshtml
@model ML.Departamento
@{
    ViewData["Title"] = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2 class="text-center">Agregar Nuevo Departamento</h2>
        </div>
    </div>
    <hr />
    <div class="row">
        <div class="col-md-12">
            @using (Html.BeginForm("Form", "Departamento", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <div class="form-horizontal">
                    @if (Model != null)
                    {
                        <div class="form-group">
                            <div class="col-md-3">
                                @Html.LabelFor(model => model.IdDepartamento, new { @class = "visually-hidden" })
                                @Html.TextBoxFor(model => model.IdDepartamento, new { @class = "visually-hidden form-control" })
                            </div>
                        </div>
                    }

                    <div class="row">

                        <div class="col-md-4">
                            @Html.LabelFor(model => model.Descripcion)
                            <div class="input-group mb-3">
                                <span class="input-group-text" id="basic-addon1"><i class="fa-solid fa-list"></i></span>
                                @Html.TextBoxFor(model => model.Descripcion, new { @class = "form-control", @id = "datepicker", @autocomplete = "false" })
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <a><input type="submit" value="Guardar" class="btn btn-success col-md-12" id="xlsx" /></a>
                            </div>
                            <div class="col-md-6">
                                <a href="@Url.Action("GetAll","Departamento")"><input type="button" value="Cancelar" class="btn btn-danger col-md-12" id="txt" /></a>
                            </div>
                        </div>

                    </div>
                </div>
            }
        </div>
    </div>
</div>

PL/Views/Departamento/GetAll.cshtml
@model ML.Departamento
@{
    ViewData["Title"] = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <h2>Departamentos</h2>
        <p>Agregar, Eliminar, Modificar los Departamentos</p>
    </div>
    <hr />

    <div class="row">
        <div style="float:right">
            @Html.ActionLink("Agregar", "Form", "Departamento", htmlAttributes: new { @class = "btn btn-success" })
        </div>
    </div>
    <hr />

    <div class="row">
        @if (Model.Departamentos != null)
        {
            <table class="table table-bordered table-responsive table-hover">
            <thead>
                <tr>
                    <td class="text-center" style=" font-weight:bold;">Editar</td>
                    
                    <td style="display: none;">IdDepartamento</td>
                    <td class="text-center" style=" font-weight:bold;">Descripción</td>
                    
                    <td class="text-center" style=" font-weight:bold;">Eliminar</td>
                </tr>
            </thead>
            
            <tbody>
                @foreach (ML.Departamento departamento in Model.Departamentos)
                {
                    <tr>
                        
                        <td class="text-center"><a class="btn btn-warning" href="@Url.Action("Form", "Departamento", new { IdDepartamento = departamento.IdDepartamento })"></a></td>
                        
                        <td style="display: none;">@departamento.IdDepartamento</td>
                        <td>@departamento.Descripcion</td>
                        
                        <td class="text-center"><a class="btn btn-danger" href="@Url.Action("Delete", "Departamento", new { IdDepartamento = departamento.IdDepartamento })" onclick="return confirm('Estas seguro que deseas inactivar este registro?');"></a></td>
                    </tr>
                }
            </tbody>
        </table>
        }
    </div>
</div>

PL/Views/Departamento/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Message</h5>
            </div>
            <div class="modal-footer">
                @Html.ActionLink("Regresar", "GetAll", "Departamento", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

<script>
    $('#modalValidacion').modal();
</script>

PL/Views/Empleado/Form.cshtml
@model ML.Empleado
@{
    ViewData["Title"] = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2 class="text-center">Agregar Nuevo Empleado</h2>
        </div>
    </div>
    <hr />
    <div class="row">
        <div class="col-md-12">
            @using (Html.BeginForm("Form", "Empleado", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <div class="form-horizontal">
                    @if (Model != null)
                    {
                        <div class="form-group">
                            <div class="col-md-3">
                                @Html.LabelFor(model => model.IdEmpleado, new { @class = "visually-hidden" })
                                @Html.TextBoxFor(model => model.IdEmpleado, new { @class = "visually-hidden form-control" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-3">
                                @Html.LabelFor(model => model.Sueldo.IdSueldo, new { @class = "visually-hidden" })
                                @Html.TextBoxFor(model => model.Sueldo.IdSueldo, new { @class = "visually-hidden form-control" })
                            </div>
                        </div>
                    }

                    <div class="row">

                        <div class="col-md-4">
                            @Html.LabelFor(model => model.Nombre)
                            <div class="input-group mb-3">
                                <span class="input-group-text" id="basic-addon1"><i class="fa-solid fa-list"></i></span>
                                @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control", @autocomplete = "false" })
                            </div>
                        </div>

                        <div class="col-md-4">
                            @Html.LabelFor(model => model.FechaIngreso)
                            <div class="input-group mb-3">
                                <span class="input-group-text" id="basic-addon1"><i class="fa-solid fa-list"></i></span>
                                @Html.TextBoxFor(model => model.FechaIngreso, new { @class = "form-control readonly1", @type = "date", @min = "2024-01-01", @max = "2050-01-01" })
                            </div>
                        </div>


                        <div class="col-md-4">
                            @Html.LabelFor(model => model.FechaNacimiento)
                            <div class="input-group mb-3">
                                <span class="input-group-text" id="basic-addon1"><i class="fa-solid fa-list"></i></span>
                                @Html.TextBoxFor(model => model.FechaNacimiento, new { @class = "form-control readonly2", @type = "date", @min = "1900-01-01", @max = "2050-01-01" })
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-4">
                            @Html.LabelFor(model => model.Departamento)
                            <div class="input-group mb-3">
                                <span class="input-group-text" id="basic-addon1"><i class="fa-solid fa-globe" style="color:darkcyan"></i></span>
                                @Html.DropDownListFor(model => model.Departamento.IdDepartamento, new SelectList(Model.Departamento.Departamentos, "IdDepartamento", "Descripcion"), "Selecciona", new { @class = "form-control", @id = "ddlDepartamento" })
                            </div>
                        </div>

                        <div class="col-md-4">
                            @Html.LabelFor(model => model.Sueldo.Sueldo1)
                            <div class="input-group mb-3">
                                <span class="input-group-text" id="basic-addon1"><i class="fa-solid fa-list"></i></span>
                                @Html.TextBoxFor(model => model.Sueldo.Sueldo1, new { @class = "form-control", @autocomplete = "false" })
                            </div>
                        </div>

                        <div class="col-md-4">
                            @Html.LabelFor(model => model.Sueldo.FormaPago)
                            <div class="input-group mb-3">
                                <span class="input-group-text" id="basic-addon1"><i class="fa-solid fa-list"></i></span>
                                @Html.TextBoxFor(model => model.Sueldo.FormaPago, new { @class = "form-control", @autocomplete = "false" })
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="row">
                            <div class="col-md-6">
                                <a><input type="submit" value="Guardar" class="btn btn-success col-md-12" id="xlsx" /></a>
                            </div>
                            <div class="col-md-6">
                                <a href="@Url.Action("GetAll","Empleado")"><input type="button" value="Cancelar" class="btn btn-danger col-md-12" id="txt" /></a>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

@section scripts
{
    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>

    <script type="text/javascript">
        $(".readonly1").keydown(function (e) {
            e.preventDefault();
        });

        var fechaIngreso = new Date('@Model.FechaIngreso.ToString("yyyy-MM-dd")');
        $(".readonly1").val(fechaIngreso.toISOString().slice(0, 10));
        
        $(".readonly2").keydown(function (e) {
            e.preventDefault();
        });

        var fechaNacimiento = new Date('@Model.FechaNacimiento.ToString("yyyy-MM-dd")');
        $(".readonly2").val(fechaNacimiento.toISOString().slice(0, 10));
    </script>
}

PL/Views/Empleado/GetAll.cshtml
@model ML.Empleado
@{
    ViewData["Title"] = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <div class="row">
        <h2>Empleados</h2>
        <p>Agregar, Eliminar, Modificar los Empleados</p>
    </div>
    <hr />

    <div class="row">
        <div style="float:right">
            @Html.ActionLink("Agregar", "Form", "Empleado", htmlAttributes: new { @class = "btn btn-success" })
        </div>
    </div>
    <hr />

    <div class="row">
        @if (Model.Empleados != null)
        {
            <table class="table table-bordered table-responsive table-hover">
                <thead>
                    <tr>
                        <td class="text-center" style=" font-weight:bold;">Editar</td>

                        <td style="display: none;">IdEmpleado</td>
                        <td class="text-center" style=" font-weight:bold;">Nombre</td>
                        <td class="text-center" style=" font-weight:bold;">Fecha Ingreso</td>
                        <td class="text-center" style=" font-weight:bold;">Fecha Nacimiento</td>
                        <td style="display: none;">IdDepartamento</td>
                        <td class="text-center" style=" font-weight:bold;">Departamento</td>
                        <td style="display: none;">IdSalario</td>
                        <td class="text-center" style=" font-weight:bold;">Salario</td>
                        <td class="text-center" style=" font-weight:bold;">Forma de Pago</td>

                        <td class="text-center" style=" font-weight:bold;">Eliminar</td>
                    </tr>
                </thead>

                <tbody>
                    @foreach (ML.Empleado empleado in Model.Empleados)
                    {
                        <tr>

                            <td class="text-center"><a class="btn btn-warning" href="@Url.Action("Form", "Empleado", new { IdEmpleado = empleado.IdEmpleado })"></a></td>

                            <td style="display: none;">@empleado.IdEmpleado</td>
                            <td>@empleado.Nombre</td>
                            <td>@empleado.FechaIngreso.ToString("dd/MM/yyyy")</td>
                            <td>@empleado.FechaNacimiento.ToString("dd/MM/yyyy")</td>
                            <td style="display: none;">@empleado.Departamento.IdDepartamento</td>
                            <td>@empleado.Departamento.Descripcion</td>
                            <td style="display: none;">@empleado.Sueldo.IdSueldo</td>
                            <td>@empleado.Sueldo.Sueldo1</td>
                            <td>@empleado.Sueldo.FormaPago</td>

                            <td class="text-center"><a class="btn btn-danger" href="@Url.Action("Delete", "Empleado", new { IdEmpleado = empleado.IdEmpleado, IdSueldo = empleado.Sueldo.IdSueldo })" onclick="return confirm('Estas seguro que deseas inactivar este registro?');"></a></td>
                        </tr>
                    }
                </tbody>
            </table>
        }
    </div>
</div>

PL/Views/Empleado/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Message</h5>
            </div>
            <div class="modal-footer">
                @Html.ActionLink("Regresar", "GetAll", "Empleado", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

<script>
    $('#modalValidacion').modal();
</script>

PL/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PL.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PL</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Departamento" asp-action="GetAll">Departamentos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Empleado" asp-action="GetAll">Empleados</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - PL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>